### ISSUE TITLE
Fix emergency response build

### ISSUE THREAD

**Issue by clemf** [hackoregon/civic#11]
Emergency response dies when trying to start the dev server:
```sh
yarn start v0.27.5
$ npm-run-all --parallel test:watch start:dev
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn babel-node ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
error Command failed with exit code 1.
ERROR: "start:dev" exited with 1.
error Command failed with exit code 1.
```

**Comment by MikeTheCanuck** [comment]
I don't know if this is important to resolving this Error, but when I first run `npm install` it ends with these two warnings:

```
npm WARN react-selectize@2.1.0 requires a peer of react-addons-css-transition-group@^0.14.0 || ^15.0.0 but none was installed.
npm WARN react-selectize@2.1.0 requires a peer of react-addons-shallow-compare@^0.14.0 || ^15.0.0 but none was installed.
```

**Comment by MikeTheCanuck** [comment]
As of #37 (or perhaps previously), the `emergency-response` package will run without errors when following the current README, whose command sequence is this:

```
nvm use
yarn bootstrap
yarn build
cd packages/emergency-response
yarn start
```
