### ISSUE TITLE
[housing] Deprecated include of L.Mixin.Events reported when running yarn start

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic#32]
Amongst the debug spew emitted during the use of `yarn start` is this warning:

```
Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead. Error
    at checkDeprecatedMixinEvents (/Users/mike/code/HackOregon/civic/node_modules/leaflet/src/core/Class.js:123:47)
    at Function.Class.extend (/Users/mike/code/HackOregon/civic/node_modules/leaflet/src/core/Class.js:51:3)
    at /Users/mike/code/HackOregon/civic/packages/housing/src/externals/leafletPattern.js:14:21
    at Object.<anonymous> (/Users/mike/code/HackOregon/civic/packages/housing/src/externals/leafletPattern.js:10:2)
    at Module._compile (module.js:570:32)
    at loader (/Users/mike/code/HackOregon/civic/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/mike/code/HackOregon/civic/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mike/code/HackOregon/civic/packages/housing/src/components/CrossHatch/leafletCrosshatch.js:2:1)
    at Module._compile (module.js:570:32)
    at loader (/Users/mike/code/HackOregon/civic/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/mike/code/HackOregon/civic/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mike/code/HackOregon/civic/packages/housing/src/components/CrossHatch/CrossHatch.test.js:4:1)
    at Module._compile (module.js:570:32)
    at loader (/Users/mike/code/HackOregon/civic/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/mike/code/HackOregon/civic/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /Users/mike/code/HackOregon/civic/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/mike/code/HackOregon/civic/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/Users/mike/code/HackOregon/civic/node_modules/mocha/lib/mocha.js:514:10)
    at loadAndRun (/Users/mike/code/HackOregon/civic/node_modules/mocha/bin/_mocha:437:22)
    at rerun (/Users/mike/code/HackOregon/civic/node_modules/mocha/bin/_mocha:465:5)
    at /Users/mike/code/HackOregon/civic/node_modules/mocha/bin/_mocha:473:7
    at StatWatcher.<anonymous> (/Users/mike/code/HackOregon/civic/node_modules/mocha/lib/utils.js:193:9)
    at emitTwo (events.js:106:13)
    at StatWatcher.emit (events.js:191:7)
    at StatWatcher._handle.onchange (fs.js:1501:10)
```

Repro steps:

```
cd civic
nvm use
yarn bootstrap
cd packages/housing
yarn start
```
(I also requested the page in Chrome from http://localhost:3000/, but not sure that's necessary to spawn this warning)

**Comment by DavideDaniel** [comment]
We might have to either stop using this leaflet package, or contribute to their project to fix this, or update to newer version if available.

**Comment by MikeTheCanuck** [comment]
As of #37 (or perhaps previously), I no longer see this warning when following the current README, whose command sequence is this:

```
nvm use
yarn bootstrap
yarn build
cd packages/emergency-response
yarn start
```
