### ISSUE TITLE
Storybook continuous delivery failing

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#471]
The latest version of Storybook is not deploying to the [hosted storybook](https://hackoregon.github.io/civic/), which uses gh-pages. It looks like it's failing at the Travis request.

https://travis-ci.org/hackoregon/civic/requests
```Not found: hackoregon/civic/.travis.yml@02aa5d5e34d5a7c6```

#45 and #105 have details on the Storybook CD implementation

**Comment by jaronheard** [comment]
The `yarn run deploy-storybook -- --ci`  command runs fine locally, but on Travis it errors out like this:

```
yarn run deploy-storybook -- --ci
yarn run v1.15.2
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
$ BABEL_ENV=esm storybook-to-ghpages --ci
=> Getting the git remote URL
   executing: git config --get remote.origin.url
=> Building storybook for: @hackoregon/civic
   executing: build-storybook  -o out5370
/home/travis/build/hackoregon/civic/node_modules/@storybook/storybook-deployer/src/utils.js:14
  throw new Error(
  ^
Error: Exec code(134) on executing: build-storybook  -o out5370
undefined
    at Object.exec (/home/travis/build/hackoregon/civic/node_modules/@storybook/storybook-deployer/src/utils.js:14:9)
    at buildStorybook (/home/travis/build/hackoregon/civic/node_modules/@storybook/storybook-deployer/src/build.js:18:18)
    at module.exports (/home/travis/build/hackoregon/civic/node_modules/@storybook/storybook-deployer/src/build.js:81:5)
    at Object.<anonymous> (/home/travis/build/hackoregon/civic/node_modules/@storybook/storybook-deployer/bin/storybook_to_ghpages:24:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make[1]: *** [deploy-component-library] Error 1
make[1]: Leaving directory `/home/travis/build/hackoregon/civic'
make: *** [deploy] Error 2
```

**Comment by jaronheard** [comment]
#561 addressed
