### ISSUE TITLE
component-library not publishing ci version to npm

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/civic#762]
## Description

There have been changes to the component library that should have resulted in published `ci` versions to npm, but it looks like it hasn't been published in a few weeks.
<img width="802" alt="image" src="https://user-images.githubusercontent.com/7065695/62974835-e6d25480-bdcd-11e9-9520-0a3b1aefbdf9.png">

### Expected result

Should publish @hackoregon/component-library ci version to npm when changes are made to the component-library package.

### Actual result

Hasn't published in 14 days

**Comment by jaronheard** [comment]
This also breaks storybook deployment, because we run the publishing scripts before we publish the component-library.

```
$ lerna publish --canary --yes --preid ci --npm-tag=ci -m '(🐦ci-canary): publish %s'

WARN deprecated --npm-tag has been renamed --dist-tag

lerna notice cli v3.13.1

lerna info ci enabled

lerna info canary enabled

lerna WARN Yarn's registry proxy is broken, replacing with public npm registry

lerna WARN If you don't have an npm token, you should exit and run `npm login`

lerna info Assuming all packages changed

Found 5 packages to publish:

 - @hackoregon/civic-babel-presets => null-ci.465+61c93f4

 - @hackoregon/component-library => null-ci.465+61c93f4

 - @hackoregon/dev-server => null-ci.465+61c93f4

 - @hackoregon/mock-wrapper => null-ci.465+61c93f4

 - @hackoregon/webpack-common => null-ci.465+61c93f4

lerna info auto-confirmed 

lerna info publish Publishing packages to npm...

lerna info Verifying npm credentials

lerna http fetch GET 200 https://registry.npmjs.org/-/npm/v1/user 572ms

lerna http fetch GET 200 https://registry.npmjs.org/-/org/jaronheard/package?format=cli 147ms

lerna ERR! Error: Invalid version: "null-ci.465+61c93f4"

lerna ERR!     at Object.fixVersionField (/home/travis/build/hackoregon/civic/node_modules/normalize-package-data/lib/fixer.js:191:13)

lerna ERR!     at /home/travis/build/hackoregon/civic/node_modules/normalize-package-data/lib/normalize.js:32:38

lerna ERR!     at Array.forEach (<anonymous>)

lerna ERR!     at normalize (/home/travis/build/hackoregon/civic/node_modules/normalize-package-data/lib/normalize.js:31:15)

lerna ERR!     at final (/home/travis/build/hackoregon/civic/node_modules/read-package-json/read-json.js:411:5)

lerna ERR!     at then (/home/travis/build/hackoregon/civic/node_modules/read-package-json/read-json.js:160:5)

lerna ERR!     at /home/travis/build/hackoregon/civic/node_modules/read-package-json/read-json.js:280:12

lerna ERR!     at /home/travis/build/hackoregon/civic/node_modules/graceful-fs/graceful-fs.js:90:16

lerna ERR! lerna Invalid version: "null-ci.465+61c93f4"

error Command failed with exit code 1.
```
